name: libadwaita_bitsdojo
description: A libadwaita package for providing an extension to AdwActions for bitsdojo_window package
version: 0.5.2
homepage: https://github.com/gtk-flutter/libadwaita_plugins/tree/main/libadwaita_bitsdojo

publish: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  bitsdojo_window_linux: ">=0.1.1 <2.0.0"
  bitsdojo_window_macos: ">=0.1.0 <2.0.0"
  bitsdojo_window_platform_interface: ">=0.1.0 <2.0.0"
  bitsdojo_window_windows: ">=0.1.0 <2.0.0"
  flutter:
    sdk: flutter
  libadwaita_core:
    path: ../libadwaita_core

dev_dependencies: 
  very_good_analysis: ^2.4.0

flutter: