name: libadwaita_bitsdojo
description: A libadwaita package to get platformAppWindow object from 
version: 0.5.0
homepage:

environment:
  sdk: ">=2.16.0-134.5.beta <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  bitsdojo_window: ">=0.1.1+1 <1.0.0"
  flutter:
    sdk: flutter

dev_dependencies: 
  very_good_analysis: ^2.4.0

flutter: