name: libadwaita_searchbar
description: A libadwaita package to get a search bar in your app, based on easy_autocomplete
version: 0.5.0
homepage:

environment:
  sdk: ">=2.16.0-134.5.beta <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  easy_autocomplete: ">=1.5.0 <2.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis: ^2.4.0

flutter: