name: libadwaita_searchbar
description: A libadwaita package to get a search bar in your app, for autosuggestions use libadwaita_searchbar_ac
version: 0.5.3+1
homepage: https://github.com/gtk-flutter/libadwaita_plugins/tree/main/libadwaita_searchbar

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis: ^2.4.0

flutter: