name: libadwaita_core
description: A libadwaita package for providing AdwControls and AdwActions for AdwHeaderBar
version: 0.5.0
homepage: https://github.com/gtk-flutter/libadwaita_plugins/tree/main/libadwaita_core

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis: ^2.4.0

flutter: