name: libadwaita_titlebar_buttons
description: A libadwaita package for providing an extension to AdwControls for titlebar_buttons package
version: 0.5.1+1
repository: https://github.com/gtk-flutter/libadwaita_plugins/tree/main/libadwaita_titlebar_buttons

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  libadwaita_core: ">=0.5.3 <1.0.0"
  titlebar_buttons: ">=1.0.0 <2.0.0"

dev_dependencies: 
  very_good_analysis: ^2.4.0

flutter: